Repository wecode-bootcamp-korea/25-1st-NULLFICTION-backend, pull requests merged in 2021-10, with the labels that each got.

#4 Add : products 앱 view 작성 (상품목록, 상세페이지)
  nullfiction/urls.py
  products/urls.py
  products/views.py
  requirements.txt
Labels: Status: 수정 요청

#5 Add: 로그인 데코레이터 추가
  cart/views.py
  users/utils.py
Labels: Status: 리뷰 요청

#8 <Refactor> cart view 리팩토링
  cart/views.py
Labels: Status: Accepted
